const AIRDROP_ID = `YOUR_AIRDROP_ID`;
const AIRDROP_ADDRESS = "YOUR AIDROP ADDRESS"
const TELEGRAM_TOKEN = "YOUR TELEGRAM TOKEN"
const CODEX_CREDENTIAL = "YOUR PASSWORD TO ENCRYPTED KEY"

module.exports = {
    AIRDROP_ID,
    AIRDROP_ADDRESS,
    TELEGRAM_TOKEN,
    CODEX_CREDENTIAL
}